// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Neodain.proto
#ifndef GRPC_Neodain_2eproto__INCLUDED
#define GRPC_Neodain_2eproto__INCLUDED

#include "Neodain.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class NeodainEventService final {
 public:
  static constexpr char const* service_full_name() {
    return "NeodainEventService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::NEODAIN_EVENT_RESP* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NEODAIN_EVENT_RESP>> AsyncpdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NEODAIN_EVENT_RESP>>(AsyncpdNeodainEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NEODAIN_EVENT_RESP>> PrepareAsyncpdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NEODAIN_EVENT_RESP>>(PrepareAsyncpdNeodainEventRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response, std::function<void(::grpc::Status)>) = 0;
      virtual void pdNeodainEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NEODAIN_EVENT_RESP* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void pdNeodainEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NEODAIN_EVENT_RESP* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void pdNeodainEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NEODAIN_EVENT_RESP* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NEODAIN_EVENT_RESP>* AsyncpdNeodainEventRaw(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NEODAIN_EVENT_RESP>* PrepareAsyncpdNeodainEventRaw(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::NEODAIN_EVENT_RESP* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NEODAIN_EVENT_RESP>> AsyncpdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NEODAIN_EVENT_RESP>>(AsyncpdNeodainEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NEODAIN_EVENT_RESP>> PrepareAsyncpdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NEODAIN_EVENT_RESP>>(PrepareAsyncpdNeodainEventRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response, std::function<void(::grpc::Status)>) override;
      void pdNeodainEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NEODAIN_EVENT_RESP* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void pdNeodainEvent(::grpc::ClientContext* context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void pdNeodainEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NEODAIN_EVENT_RESP* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void pdNeodainEvent(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NEODAIN_EVENT_RESP* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NEODAIN_EVENT_RESP>* AsyncpdNeodainEventRaw(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NEODAIN_EVENT_RESP>* PrepareAsyncpdNeodainEventRaw(::grpc::ClientContext* context, const ::NEODAIN_EVENT& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_pdNeodainEvent_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status pdNeodainEvent(::grpc::ServerContext* context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_pdNeodainEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_pdNeodainEvent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_pdNeodainEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdNeodainEvent(::grpc::ServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpdNeodainEvent(::grpc::ServerContext* context, ::NEODAIN_EVENT* request, ::grpc::ServerAsyncResponseWriter< ::NEODAIN_EVENT_RESP>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_pdNeodainEvent<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_pdNeodainEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_pdNeodainEvent() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::NEODAIN_EVENT, ::NEODAIN_EVENT_RESP>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::NEODAIN_EVENT* request, ::NEODAIN_EVENT_RESP* response) { return this->pdNeodainEvent(context, request, response); }));}
    void SetMessageAllocatorFor_pdNeodainEvent(
        ::grpc::experimental::MessageAllocator< ::NEODAIN_EVENT, ::NEODAIN_EVENT_RESP>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::NEODAIN_EVENT, ::NEODAIN_EVENT_RESP>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_pdNeodainEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdNeodainEvent(::grpc::ServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* pdNeodainEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* pdNeodainEvent(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_pdNeodainEvent<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_pdNeodainEvent<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_pdNeodainEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_pdNeodainEvent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_pdNeodainEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdNeodainEvent(::grpc::ServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_pdNeodainEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_pdNeodainEvent() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_pdNeodainEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdNeodainEvent(::grpc::ServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpdNeodainEvent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_pdNeodainEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_pdNeodainEvent() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->pdNeodainEvent(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_pdNeodainEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdNeodainEvent(::grpc::ServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* pdNeodainEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* pdNeodainEvent(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_pdNeodainEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_pdNeodainEvent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NEODAIN_EVENT, ::NEODAIN_EVENT_RESP>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::NEODAIN_EVENT, ::NEODAIN_EVENT_RESP>* streamer) {
                       return this->StreamedpdNeodainEvent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_pdNeodainEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status pdNeodainEvent(::grpc::ServerContext* /*context*/, const ::NEODAIN_EVENT* /*request*/, ::NEODAIN_EVENT_RESP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedpdNeodainEvent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NEODAIN_EVENT,::NEODAIN_EVENT_RESP>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_pdNeodainEvent<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_pdNeodainEvent<Service > StreamedService;
};

class ActiveNeodainInfoService final {
 public:
  static constexpr char const* service_full_name() {
    return "ActiveNeodainInfoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG& request, ::ACTIVE_NEODAIN_INFO* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ACTIVE_NEODAIN_INFO>> AsyncpdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ACTIVE_NEODAIN_INFO>>(AsyncpdActiveNeodainInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ACTIVE_NEODAIN_INFO>> PrepareAsyncpdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ACTIVE_NEODAIN_INFO>>(PrepareAsyncpdActiveNeodainInfoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response, std::function<void(::grpc::Status)>) = 0;
      virtual void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ACTIVE_NEODAIN_INFO* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ACTIVE_NEODAIN_INFO>* AsyncpdActiveNeodainInfoRaw(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ACTIVE_NEODAIN_INFO>* PrepareAsyncpdActiveNeodainInfoRaw(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG& request, ::ACTIVE_NEODAIN_INFO* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ACTIVE_NEODAIN_INFO>> AsyncpdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ACTIVE_NEODAIN_INFO>>(AsyncpdActiveNeodainInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ACTIVE_NEODAIN_INFO>> PrepareAsyncpdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ACTIVE_NEODAIN_INFO>>(PrepareAsyncpdActiveNeodainInfoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response, std::function<void(::grpc::Status)>) override;
      void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ACTIVE_NEODAIN_INFO* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void pdActiveNeodainInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ACTIVE_NEODAIN_INFO* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ACTIVE_NEODAIN_INFO>* AsyncpdActiveNeodainInfoRaw(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ACTIVE_NEODAIN_INFO>* PrepareAsyncpdActiveNeodainInfoRaw(::grpc::ClientContext* context, const ::NULL_MSG& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_pdActiveNeodainInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status pdActiveNeodainInfo(::grpc::ServerContext* context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_pdActiveNeodainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_pdActiveNeodainInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_pdActiveNeodainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdActiveNeodainInfo(::grpc::ServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpdActiveNeodainInfo(::grpc::ServerContext* context, ::NULL_MSG* request, ::grpc::ServerAsyncResponseWriter< ::ACTIVE_NEODAIN_INFO>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_pdActiveNeodainInfo<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_pdActiveNeodainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_pdActiveNeodainInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::NULL_MSG, ::ACTIVE_NEODAIN_INFO>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::NULL_MSG* request, ::ACTIVE_NEODAIN_INFO* response) { return this->pdActiveNeodainInfo(context, request, response); }));}
    void SetMessageAllocatorFor_pdActiveNeodainInfo(
        ::grpc::experimental::MessageAllocator< ::NULL_MSG, ::ACTIVE_NEODAIN_INFO>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::NULL_MSG, ::ACTIVE_NEODAIN_INFO>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_pdActiveNeodainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdActiveNeodainInfo(::grpc::ServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* pdActiveNeodainInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* pdActiveNeodainInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_pdActiveNeodainInfo<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_pdActiveNeodainInfo<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_pdActiveNeodainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_pdActiveNeodainInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_pdActiveNeodainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdActiveNeodainInfo(::grpc::ServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_pdActiveNeodainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_pdActiveNeodainInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_pdActiveNeodainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdActiveNeodainInfo(::grpc::ServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestpdActiveNeodainInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_pdActiveNeodainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_pdActiveNeodainInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->pdActiveNeodainInfo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_pdActiveNeodainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pdActiveNeodainInfo(::grpc::ServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* pdActiveNeodainInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* pdActiveNeodainInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_pdActiveNeodainInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_pdActiveNeodainInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NULL_MSG, ::ACTIVE_NEODAIN_INFO>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::NULL_MSG, ::ACTIVE_NEODAIN_INFO>* streamer) {
                       return this->StreamedpdActiveNeodainInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_pdActiveNeodainInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status pdActiveNeodainInfo(::grpc::ServerContext* /*context*/, const ::NULL_MSG* /*request*/, ::ACTIVE_NEODAIN_INFO* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedpdActiveNeodainInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NULL_MSG,::ACTIVE_NEODAIN_INFO>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_pdActiveNeodainInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_pdActiveNeodainInfo<Service > StreamedService;
};


#endif  // GRPC_Neodain_2eproto__INCLUDED
