// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: command.proto

#include "command.pb.h"
#include "command.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Cmf {

static const char* Commander_method_names[] = {
  "/Cmf.Commander/Send",
};

std::unique_ptr< Commander::Stub> Commander::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Commander::Stub> stub(new Commander::Stub(channel));
  return stub;
}

Commander::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Send_(Commander_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Commander::Stub::Send(::grpc::ClientContext* context, const ::Cmf::Request& request, ::Cmf::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Send_, context, request, response);
}

void Commander::Stub::experimental_async::Send(::grpc::ClientContext* context, const ::Cmf::Request* request, ::Cmf::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, std::move(f));
}

void Commander::Stub::experimental_async::Send(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Cmf::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, std::move(f));
}

void Commander::Stub::experimental_async::Send(::grpc::ClientContext* context, const ::Cmf::Request* request, ::Cmf::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, reactor);
}

void Commander::Stub::experimental_async::Send(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Cmf::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Cmf::Response>* Commander::Stub::AsyncSendRaw(::grpc::ClientContext* context, const ::Cmf::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Cmf::Response>::Create(channel_.get(), cq, rpcmethod_Send_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Cmf::Response>* Commander::Stub::PrepareAsyncSendRaw(::grpc::ClientContext* context, const ::Cmf::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Cmf::Response>::Create(channel_.get(), cq, rpcmethod_Send_, context, request, false);
}

Commander::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Commander_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Commander::Service, ::Cmf::Request, ::Cmf::Response>(
          [](Commander::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::Cmf::Request* req,
             ::Cmf::Response* resp) {
               return service->Send(ctx, req, resp);
             }, this)));
}

Commander::Service::~Service() {
}

::grpc::Status Commander::Service::Send(::grpc::ServerContext* context, const ::Cmf::Request* request, ::Cmf::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Cmf

